version: '3'

services:
  sbproducer:
    build:
      context: ./sb-kafka-producer
      dockerfile: Dockerfile
    environment:
      - BROKER=kafka1:19092
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
  sbconsumer:
    build:
      context: ./sb-kafka-consumer
      dockerfile: Dockerfile
    environment:
      - BROKER=kafka2:19093
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka2:19093
      - MESSAGE_PROCESSING_TIME=0
